# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dfmetrics',
                'doc_host': 'https://Santiago-R.github.io',
                'git_url': 'https://github.com/Santiago-R/dfmetrics',
                'lib_path': 'dfmetrics'},
  'syms': { 'dfmetrics.core': { 'dfmetrics.core.branch': ('core.html#branch', 'dfmetrics/core.py'),
                                'dfmetrics.core.keycheck': ('core.html#keycheck', 'dfmetrics/core.py')}}}
